services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: prn232_lms_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P \"Your_password123\" -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: PRN232.LMS.API/Dockerfile
    container_name: prn232_lms_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=PRN232_LMS;User Id=sa;Password=Your_password123;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8080:8080"
